### ISSUE TITLE
Add emoji picker field.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-fields#17]
https://github.com/missive/emoji-mart

**Comment by andrewculver** [comment]
Another library/guide that's out there: https://sowenjub.me/writes/emoji-picker-controller-with-stimulus-js/ using https://github.com/joeattardi/picmo .

**Comment by andrewculver** [comment]
General feeling is that `emoji-mart` feels cleaner from a UI perspective.

**Comment by existentialmutt** [comment]
Looks pretty straightforward.  I can ahead with emoji-mart using the Stimulus controller technique in the article.
