### ISSUE TITLE
Add "Select All" and "Reset" options to `options`.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-fields#20]
The `options` field partial currently look like this when `multiple: true`:

<img width="161" alt="Screen Shot 2022-07-14 at 11 53 55 AM" src="https://user-images.githubusercontent.com/217218/179061227-f39c6533-28ae-4606-84d9-14d9f9c2e0d1.png">

I'm currently working on a form where the list of options could be dozens, and I'd like to add a little link in the help text portion that allows people to "Select All".

Also, in my current example, the model might have some subset of options preselected when creating the model. Once the user selects more or deselects some or selects all, I'd like them to be presented with a little link that allows them to "Reset to Default".

**Comment by danieldpence** [comment]
Hey @pascallaliberte I think you could probably reuse/repurpose some of the code that lives in [action_models](https://github.com/andrewculver/bullet_train-action_models/blob/main/app/javascript/controllers/bulk_actions_controller.js#L41-L53) as a good starting point.

**Comment by pascallaliberte** [comment]
@danieldpence Yeah for sure, that's the plan

**Comment by pascallaliberte** [comment]
@andrewculver 

In your help text:
1. is it that the "Select All" button is going to be in the help text, or 
2. is it that the help text will have a link to "Enable Select All", which will show a "Select All" checkbox or button below the list?

This will help me judge what to add as a standard feature and what to carve out as a documented alternative approach.

**Comment by andrewculver** [comment]
@pascallaliberte Actually, we probably shouldn't put this in the help text. Instead, it should just be another part of the field section. Could be a button or could be a link. Either way, the button/link is "Select All" and it results in all the items being selected.

**Comment by pascallaliberte** [comment]
@andrewculver Here's where I'm at.

The two PRs above have some progress. There's one piece of feedback I need from you, and then I could optionally extract out some duplicated functionality for further optimization.

Your feedback on an idea:
Do you want the "Reset To Default" button to be a core feature of the options field (through a toggle) or a possible feature using instructions in the docs with accompanying code?

Here's my example if it's not a code feature and instead simply documented:

### Enable Select All and a "Reset to Default" button when multiple

You can easily add a "Select All" functionality to a multiple options field.

To add the "All" checkbox above: 

```erb
<%= render 'shared/fields/options',
  method: :tailwind_colors,
  html_options: {autofocus: true},
  multiple: true, show_select_all_top: true
%>
```
<img width="476" alt="CleanShot 2022-08-11 at 22 02 59@2x" src="https://user-images.githubusercontent.com/104179/184271499-fc7e0259-cd33-4352-ac7d-ab8de8ded18d.png">

To add the "All" checkbox below:

```erb
<%= render 'shared/fields/options',
  method: :multiple_option_values,
  multiple: true, show_select_all_bottom: true
%>
```
<img width="412" alt="CleanShot 2022-08-11 at 22 06 49@2x" src="https://user-images.githubusercontent.com/104179/184271834-fb28453b-9548-4c81-bbdb-7fe0748d1768.png">

### To add a "Reset to Default" button

![CleanShot 2022-08-11 at 22 09 18](https://user-images.githubusercontent.com/104179/184272117-0dd43465-646b-414a-b128-afd41acf561f.gif)

In your application, add a `revertible-fields_controller.js` to your `app/javascript/controllers` dir:

```js
import { Controller } from "@hotwired/stimulus"

export default class extends Controller {
  static targets = [ "field", "revertButton" ]
  static values = {
    "revertible": Boolean
  }
  
  revertFields(event) {
    this.fieldTargets.forEach(fieldTarget => {
      fieldTarget.dispatchEvent(new CustomEvent(`${this.identifier}:revert-to-original`))
    })
    this.dispatch('fields-reverted', { target: event.target })
    this.updateRevertibility()
  }
  
  updateRevertibility() {
    this.revertibleValue = this.fieldTargets.some(fieldTarget => {
      return fieldTarget.dataset[`revertibleFieldsFieldDirty`] === "true"
    })
  }
  
  revertibleValueChanged(newValue) {
    const eventName = `${this.identifier}:${(newValue === true)? "show" : "hide"}`
    this.revertButtonTarget.dispatchEvent(new CustomEvent(eventName, {
      bubbles: true
    }))
  }
  
  recordFieldOriginalValue(event) {
    const fieldTarget = event.target
    fieldTarget.dataset[`revertibleFieldsFieldOriginal`] = event.detail?.originalValue
  }
  
  updateFieldDirty(event) {
    const fieldTarget = event.target
    this.updateFieldDirtyFor(fieldTarget)
  }
  
  updateFieldDirtyFor(fieldTarget) {
    let isDirty = false
    if (fieldTarget.dataset[`revertibleFieldsFieldOriginal`] !== undefined) {
      isDirty = getValueStringOf(fieldTarget) !== fieldTarget.dataset[`revertibleFieldsFieldOriginal`]
    }
    fieldTarget.dataset[`revertibleFieldsFieldDirty`] = (isDirty? "true": "false")
    this.updateRevertibility()
  }
  
  updateFieldDirtyForAllFields() {
    this.fieldTargets.forEach(fieldTarget => {
      this.updateFieldDirtyFor(fieldTarget)
    })
    this.updateRevertibility()
  }
}

function getValueStringOf(field) {
  switch (field.type) {
    case "checkbox":
      return field.checked? "true": "false"
  }
  
  return field.value
}
```

And in your form, assuming here we're only applying it on the `#new` action, we'll wrap the `options` field and supply a new button in the `:actions_on_multiple` section.

```erb
<% unless action_name.to_sym == :new %>
  <%= render 'shared/fields/options', method: :tailwind_colors, html_options: {autofocus: true}, multiple: true, use_columns: true, show_select_all_top: true %>
<% else %>
  <div data-controller="revertible-fields" data-action="fields--field:original-recorded->revertible-fields#recordFieldOriginalValue fields--options:toggled-select-all->revertible-fields#updateFieldDirtyForAllFields">
    <%= render 'shared/fields/options', method: :tailwind_colors, html_options: {autofocus: true}, multiple: true, use_columns: true, show_select_all_top: true, option_field_options: {
      data: {
        "revertible-fields-target": "field",
        "action": "revertible-fields#updateFieldDirty revertible-fields:revert-to-original->fields--field#revert fields--field:reverted->revertible-fields#updateFieldDirty"
      }
    } do %>
      <%= content_for :actions_on_multiple do %>
        <%= tag.div class: "inline-block overflow-hidden ml-3", data: {
          "controller": "reveal",
          "action": "revertible-fields:show->reveal#show revertible-fields:hide->reveal#hide revertible-fields:fields-reverted->fields--options#updateSelectAllCheckbox",
          "reveal-open-value": "false",
          "reveal-debug-value": "true"
        } do %>
          <%= button_tag "Reset to Default", type: 'button', hidden: true, data: {
            "reveal": "",
            "transition": "",
            "revertible-fields-target": "revertButton",
            "transition-enter": "transition transform ease-out duration-150",
            "transition-enter-start": "-translate-x-[100%]",
            "transition-enter-end": "translate-x-0",
            "transition-leave": "transition transform ease-out duration-150",
            "transition-leave-start": "translate-x-0",
            "transition-leave-end": "-translate-x-[100%]",
            "action": "revertible-fields#revertFields"
          } %>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>
```

**Comment by pascallaliberte** [comment]
Made some progress today. `fields--options` will be removed and replaced entirely with a new `select-all` controller. Nothing will be left for the `fields--options` controller after extracting select-all functionality.

In another PR, I'll likely do the same with bulk-actions-controller. I'll remove select-all functionality from it and also create a public npm package for action-models, removing the need for bulk-* controllers from `bullet_train-base`

**Comment by pascallaliberte** [comment]
@andrewculver The three PRs above are ready for your review for this change.

What's not included in the PR:
* The "Reset to Default" functionality: [as explained above](https://github.com/bullet-train-co/bullet_train-fields/issues/20#issuecomment-1212665499), I opted to not include this as a default functionality for the `options` field, and suggestion instead to add the functionality at the application level. Open to discussion of course!
