### ISSUE TITLE
Color Picker - More than one instance breaks the pencil icon

### ISSUE THREAD

**Issue by pascallaliberte** [bullet-train-co/bullet_train-fields#23]
We need to make sure we can have more than one color picker instance per view.

**Comment by pascallaliberte** [comment]
@andrewculver, just a heads up:

The original library, [@simonwep/pickr](https://github.com/Simonwep/pickr), has [the issue marked as a feature request but the project is no longer maintained](https://github.com/Simonwep/pickr/issues/57).

To fix this issue, we will need to replace that library altogether or to make a first-party fork.

I'm not a fan of how the library is built, and so I'll invest a bit of time finding something else that's equivalent but more Stimulus and multi-instance friendly.

**Comment by andrewculver** [comment]
Oh man, what a pain. I love our color picker. Any chance we can try just fixing the existing library?

**Comment by andrewculver** [comment]
Although, I’m open to other library suggestions as well!

**Comment by pascallaliberte** [comment]
@andrewculver Had you ever considered a native HTML `<input type="color">`? Would save a bit of js. Pickr includes a popover-like mini library, the pickr itself...

[Here's an example (try it on your phone too)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/color#try_it)

**Comment by pascallaliberte** [comment]
What did you like most about the OG library?
What made it stand out and BT-like for you?

**Comment by pascallaliberte** [comment]
Oh [vanilla-colorful](https://iamkulykov.com/vanilla-colorful/) looks pretty!

<img width="808" alt="CleanShot 2022-07-19 at 18 39 21@2x" src="https://user-images.githubusercontent.com/104179/179860304-10f0ffe8-78a5-4553-82e2-08beae64d728.png">

It's also a web component. Slick.

<img width="436" alt="CleanShot 2022-07-19 at 18 41 31@2x" src="https://user-images.githubusercontent.com/104179/179860540-2d71143e-b3bc-4469-ae64-b3fa7d3d7692.png">

**Comment by pascallaliberte** [comment]
Ok I'm going with rebuilding a similar experience of the Pickr dialog using `vanilla-colorful` and `popperjs`, a text field and a Save button.

**Comment by andrewculver** [comment]
@pascallaliberte The native color picker is awesome. Especially on Safari. Any reason not to use it to replace pickr?

**Comment by pascallaliberte** [comment]
@andrewculver I mean I'm a fan of a browser-native option if it's minimally good across browsers and OSes.

It's an inconsistent UI across browsers, however. And I have no idea how it feels on Android or on Windows.

I think I'll be able to hide the usual browser input field and replace it with the combo of the colored circle (for preview), the hex input box (for editing) and the edit button (for the native popup).

**Comment by pascallaliberte** [comment]
@andrewculver Main reason to not use the browser-native:

**Editing the hex value is not consistent across browsers.**

In the current Picks-based color picker, the hex value is not editable and you need to click the pen icon.

![CleanShot 2022-07-21 at 15 36 36@2x](https://user-images.githubusercontent.com/104179/180301329-b0c311c6-d212-4b4d-aa6b-7e40c2035544.png)

But a pen icon with browser-native UI: no hex field available in Safari, nor in Firefox, and it's hard to get to in Chrome.
![CleanShot 2022-07-21 at 15 42 53@2x](https://user-images.githubusercontent.com/104179/180302033-afe5413a-2187-41c8-99d9-7b9de85b5fc9.png)

![CleanShot 2022-07-21 at 15 44 24@2x](https://user-images.githubusercontent.com/104179/180302261-f42e6fae-d275-4b9c-bd7f-12ee185a41a4.png)


![CleanShot 2022-07-21 at 15 41 22@2x](https://user-images.githubusercontent.com/104179/180302043-627c76ab-87fe-47a7-9ed5-e7ab27ca7be9.png)

**Comment by pascallaliberte** [comment]
All right, so an update.

I've found a way (I think) to fix Pickr to support multiple instances per page. Here's the gist:

- When instantiating Pickr, the `el` property is for a single button element. A `.btn-pickr` class selector is what causes the issue
- Also when instantiating Pickr, the `container` property should not be `body` (which is the default), but a div inside the Stimulus controller

Doing those two things, affecting both the `bullet_train-fields` repo for the Stimulus controller and `bullet_train-themes-tailwind-css` for the html partial, should fix the issue.

I have to bounce for the rest of the week, but wanted to document this.
