### ISSUE TITLE
The `code` field partial needs a `secret` option.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-fields#32]
Looking at the following view as an example:

<img width="949" alt="Screen Shot 2022-09-05 at 10 36 41 AM" src="https://user-images.githubusercontent.com/217218/188496113-6bdab9c2-09e0-4f73-9a11-8ee30508ad76.png">

We need the option to specify that "Client Secret" and "Token" are secret and shouldn't be shown completely without user action. Basically we should present them as the first five characters and then a link to show the rest:

> `fDaLt` [Show](#)

**Comment by pascallaliberte** [comment]
I'll probably be using a css-only solution using the `<details>` tag, Tailwind's `group` and `peer` selectors.

See a working demo:
https://play.tailwindcss.com/XjAzAZTCh0

This doesn't animate, and will cause a table to resize column on click the Show button. I can also [remove the disclosure triangle in Safari from the Show button via CSS](https://github.com/tailwindlabs/tailwindcss/issues/924#issuecomment-915509785).
