### ISSUE TITLE
Add password strength indicator as an option on our password fields.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-fields#7]
https://github.com/dropbox/zxcvbn

**Comment by andrewculver** [comment]
Wait for https://github.com/bullet-train-co/bullet_train-fields/issues/8 before getting started on this.

**Comment by pascallaliberte** [comment]
@jorbs  Everything should be ready to cut a release of gem + npm.

Same instructions for all of our js packages, found in RELEASE.md in bullet_train-base
