### ISSUE TITLE
Add guide on how to do local development and cut gem and npm releases.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-fields#8]

**Comment by pascallaliberte** [comment]
@andrewculver So this would replace the mention in the README to check out the RELEASE.md in bullet_train-base?

**Comment by andrewculver** [comment]
@pascallaliberte Haha, wasn't sure but now that I think about it I think we just create a `RELEASE.md` in this repo that points to the other file. I'll handle it!
